language: node_js

sudo: false

git:
  depth: 10

node_js:
  - node

env:
  matrix:
    - RUBY_VERSION=2.0

before_install:
  - rvm install $RUBY_VERSION
  - rvm use $RUBY_VERSION --fuzzy
  - export GEMDIR=$(rvm gemdir)

install:
  - travis_retry npm install
  - travis_retry gem install --no-document "jekyll:~>3.0.0" "rouge:~>1.10" "sass:~>3.4"

matrix:
  fast_finish: true
